[package]
name = "semios"
version = "0.1.0"
description = "The lightest, fastest web browser"
authors = ["danielsem65"]
edition = "2021"
license = "MIT"
repository = "https://github.com/danielsem65"
keywords = ["browser", "webview", "lightweight"]
categories = ["network"]

[lib]
name = "semios_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-http = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
percent-encoding = "2"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true
